### ISSUE TITLE
Contact hrefs are invalid

### ISSUE THREAD

**Issue by buske** [monarch-initiative/monarch-mme#10]
The contact href for matches should be an http link for that record or a mailto link to contact the contributor of the case. This does not appear to be the case for the majority of responses. Here is one example received from the monarch endpoint:

``` json
    ...,
    {
      "score": {
        "patient": 46
      },
      "patient": {
        "id": "OMIM:300848",
        "label": "Mental Retardation, X-Linked 89",
        "contact": {
          "name": "ratatouille",
          "href": "http://ratatouille.org"
        },
        "features": [
          {
            "id": "HP:0000750",
            "observed": "yes",
            "label": "Delayed speech and language development"
          }
        ]
      }
    },
    ...
```

All matches that I've seen have the href of `http://ratatouille.org`, which goes to the Disney movie's page. :)

**Comment by cmungall** [comment]
Oops, we'll fix this.

Given that our matches are to abstracted patients or models, does a uniform

```
    "contact": {
      "name": "Monarch Initiative",
      "href": "info@monarchinitiative.org"
    },
```

seem fine?

**Comment by cmungall** [comment]
errata: add mailto: to the above href

**Comment by buske** [comment]
:) Just before I said that. The email is just fine if if you don't have more specific resources for those data (e.g., http://omim.org/entry/300848).
