### ISSUE TITLE
Endpoint down?

### ISSUE THREAD

**Issue by buske** [monarch-initiative/monarch-mme#11]
The https://mme.monarchinitiative.org endpoint appears to be down. I'm getting a `503 Service Unavailable` error when I connect via browser or POST to the `/match` endpoint.

**Comment by jnguyenx** [comment]
Yes we're currently migrating our servers, it should be back by the end of
the week :)

**Comment by buske** [comment]
Great! Glad it was intentional. :)

**Comment by jnguyenx** [comment]
It's up now! :-)

**Comment by buske** [comment]
Awesome, thanks!
