### ISSUE TITLE
Support application/vnd.ga4gh.matchmaker.v1.0+json Content-Type

### ISSUE THREAD

**Issue by buske** [monarch-initiative/monarch-mme#13]
Hi! Trying to get this working with PC. It looks like `application/json` and `text/json` are the only two supported content-types. Would it be possible to support the MME API Content-Type as well (or any `...+json` content type)? E.g., 

`-H 'Content-Type: application/vnd.ga4gh.matchmaker.v1.0+json; charset=utf-8'`

Currently, this results in a `400 Bad Request`. Thanks so much!

**Comment by jnguyenx** [comment]
So I'm confused about the version check, the [specs](https://github.com/ga4gh/mme-apis/blob/master/search-api.md#versioning) says:

> If a compatible version (vX.Z where Z>=Y) is supported by the remote server, it should provide a response using this version.

For now I'm only checking that the `Accept` version sent by the client is smaller than the server one. That's what the specs are telling I believe. (Shouldn't it the way around by the way? The client should accept its current version and older versions as long as the major is the same on both side).

Now there's nothing about the version of the data sent to the server. I think that we'd like to check of the server is able to parse the data, and in this case the server version should be greater than the version provided from the `Content-type` sent from the client.

With that much constraints, the version has to be the same in the `Accept` and `Content-type` fields from the client request and in the server.

I feel like I'm missing something...

**Comment by buske** [comment]
@jnguyenx Short answer is: I agree. I think we should either use a Content-Type of `application/json` and use the Accept header to version, or just use the Content-Type for both. I believe the tech group actually chatted about this on a call at one point and agreed to use Content-Type. The client sets the Content-Type of the query, and the Content-Type of the response should be backwards-compatible with the query.

The question you touch on is a good one. What is backwards-compatibility here? I don't think it's backwards right now, but I don't think it's right, either. Because the communication is two-way, both the client and server need to communicate with the same version or a backwards-compatible one. Is it better for the server to tailor to the client, or vis a versa? Since both are MME services, it doesn't really matter. As long as the minor version is backwards compatible, both should be able to speak if they're on the same major version. Let me know if this isn't right. Otherwise we can create a GitHub issue to propose this update to the docs.

**Comment by jnguyenx** [comment]
I see. I don't think that it's a big deal right now for our MME instance, I'll keep the version check as it is and change it accordingly if another decision is made.

Thanks for the explanation!

The server should now accept the header that you asked for.
