### ISSUE TITLE
https certificate is expired

### ISSUE THREAD

**Issue by buske** [monarch-initiative/monarch-mme#15]
"mme.monarchinitiative.org uses an invalid security certificate. The certificate expired on 19 May 2016 at 15:23. The current time is 19 May 2016 at 18:41. Error code: `SEC_ERROR_EXPIRED_CERTIFICATE`"

**Comment by jnguyenx** [comment]
Should be all good to go, thanks!

**Comment by jmcmurry** [comment]
Thanks both!

Team, in the future for stuff like this that has a known expiration date,
perhaps it would be great if we could put an event with reminder on the
team calendar so that we are certain to deal before there are problems.

**Comment by buske** [comment]
And thank you all for your super-speedy replies! I it looks like you're using Let's Encrypt for your cert (nice!), so you can probably even renew it automatically in the future with a cron job.

**Comment by jnguyenx** [comment]
Yes the MME service was the first one I experimented with for ssl.
Unfortunately I didn't get the cronjob quite right. Now it should renew
itself automatically as for the our other services.
