### ISSUE TITLE
Score should be in the range [0, 1]

### ISSUE THREAD

**Issue by buske** [monarch-initiative/monarch-mme#16]
The endpoint appears to be returning percentages [0, 100.0] instead of the required [0, 1] range.

This is what a response from the endpoint currently looks like,

```
{"results":[
  {
    "score":{"patient":71.0},
    "patient":{"id":"OMIM:225750","label":"Aicardi-Goutieres Syndrome 1", ...}
  },
  ...
]}

```

**Comment by jnguyenx** [comment]
Scores are divided by 100 now.

Just to let you know, I'll be on vacations starting from tomorrow and be back mid-June.
@cmungall can answer urgent questions.

**Comment by buske** [comment]
Great, thanks so much for all your help, @jnguyenx. This should be the last thing necessary to have it all play nicely with PhenomeCentral. Should have it added to the UI shortly. Have a nice trip! :)
