### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-mme#6]
via @buske

We already have signatures for *.monarchinitiative.org, so should be straighforward. Will check with Larry

**Comment by buske** [comment]
Worth reopening? :)

**Comment by jnguyenx** [comment]
Definitely, we'll eventually move our production to another machine, we'll add https support then.

**Comment by jnguyenx** [comment]
Okay we now support https only.

I was not sure if we should still support http, so I put a redirect to https.

**Comment by buske** [comment]
I think that's the right decision.
