### ISSUE TITLE
Non-conformant features

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-mme#7]
via @buske
- version - only accepts 0.X, not 1.X (should probably update example in docs so it uses the latest version?)
- genomicFeatures - their endpoint requires the optional "type" field
- returns error "genomicFeatures and features are both empty." if either are unspecified. Also, doesn't complain if they're specified, but empty

**Comment by buske** [comment]
Thanks for entering this @cmungall. To clarify the first version point, the endpoint appears to actually parse v1.X, but it only accepts v0.X in the header.
