### ISSUE TITLE
Port documentation is out of date

### ISSUE THREAD

**Issue by buske** [monarch-initiative/monarch-mme#9]
```
$ curl -XPOST \
    -H "Accept: application/vnd.ga4gh.matchmaker.v1.0+json" \
    -H "Content-Type: application/json" -d '{
"patient":{
  "id":"test", 
  "contact":{"name":"First Last","href":"mailto:firstlast@example.com"}, 
  "genomicFeatures": [{"gene": {"id": "SRCAP"}}],
  "test": true}
}' -k http://mme.monarchinitiative.org:9000/match

curl: (7) couldn't connect to host
```

**Comment by jnguyenx** [comment]
Strange, can you access http://mme.monarchinitiative.org:9000 from a
browser?

**Comment by buske** [comment]
No, I can access it at :80 from a web browser though. Ah, it appears the docs are just a bit out of date and the webpage and the API endpoint are all on port 80.

**Comment by buske** [comment]
```
$ curl -XPOST -H "X-Auth-Token: test" \
  -H "Accept: application/vnd.ga4gh.matchmaker.v1.0+json" \
  -H "Content-Type: application/json" -d '{
"patient":{"id":"test",
  "contact":{"name":"Orion Buske","href":"mailto:orion@phenomecentral.org"},
  "genomicFeatures": [{"gene": {"id": "SRCAP"}}],
  "test": true}
}' -k https://mme.monarchinitiative.org/match

genomicFeatures not implemented on this server.
```

**Comment by jnguyenx** [comment]
Both works for me surprisingly, I'll update the doc just in case. Thanks
for spotting that.

Here's a query example:

curl -XPOST 'http://mme.monarchinitiative.org/match' -H
'Content-type:application/json' -H 'Accept:
application/vnd.ga4gh.matchmaker.v1.0+json' -d '{
   "patient":{
      "id" : "patientID",

```
  "contact":{
     "href":"http://www.ncbi.nlm.nih.gov/pubmed/22305528",
     "institution":"Childrens Hospital of Eastern Ontario",
     "name":"Lijia Huang"
  },
  "disorders":[
     {
        "id":"MIM:610536",
        "label":"#610536 MANDIBULOFACIAL DYSOSTOSIS, GUION-ALMEIDA
```

TYPE; MFDGA ;;MANDIBULOFACIAL DYSOSTOSIS WITH MICROCEPHALY; MFDM;; GROWTH
AND MENTAL RETARDATION, MANDIBULOFACIAL DYSOSTOSIS, MICROCEPHALY, AND CLEFT
PALATE"
         }
      ],
      "features":[
         {
            "id":"HP:0008773",
            "label":"Aplasia/Hypoplasia of the middle ear",
            "observed":"yes"
         },
         {
            "id":"HP:0000413",
            "label":"Atresia of the external auditory canal",
            "observed":"yes"
         },
         {
            "id":"HP:0000453",
            "label":"Choanal atresia",
            "observed":"yes"
         },
         {
            "id":"HP:0000405",
            "label":"Conductive hearing impairment",
            "observed":"yes"
         },
         {
            "id":"HP:0011451",
            "label":"Congenital microcephaly",
            "observed":"yes"
         },
         {
            "id":"HP:0011471",
            "label":"Gastrostomy tube feeding in infancy",
            "observed":"yes"
         },
         {
            "id":"HP:0010880",
            "label":"Increased nuchal translucency",
            "observed":"yes"
         },
         {
            "id":"HP:0000272",
            "label":"Malar flattening",
            "observed":"yes"
         },
         {
            "id":"HP:0000347",
            "label":"Micrognathia",
            "observed":"yes"
         },
         {
            "id":"HP:0008551",
            "label":"Microtia",
            "observed":"yes"
         },
         {
            "id":"HP:0011342",
            "label":"Mild global developmental delay",
            "observed":"yes"
         },
         {
            "id":"HP:0000545",
            "label":"Myopia",
            "observed":"yes"
         },
         {
            "id":"HP:0000384",
            "label":"Preauricular skin tag",
            "observed":"yes"
         },
         {
            "id":"HP:0001622",
            "label":"Premature birth",
            "observed":"no"
         },
         {
            "id":"HP:0009623",
            "label":"Proximal placement of thumb",
            "observed":"yes"
         }
      ],
      "genomicFeatures":[
         {
            "gene":{
               "id":"EFTUD2"
            },
            "type":{
               "id":"SO:0001587",
               "label":"STOPGAIN"
            },
            "variant":{
               "assembly":"GRCh37",
               "hgvs":"NM_004247.3(EFTUD2):c.2770CT",
               "referenceName":"17",
               "start":42929131
            }
         }
      ],
      "id":"P0000079",
      "label":"178_M43377"
   }
}'

**Comment by buske** [comment]
Yep, sorry, I just meant to show that I was now getting through to the server when I went over port 80. Even with your example, I get `couldn't connect to host` when trying over port 9000.

**Comment by jnguyenx** [comment]
Documentation updated :-)

**Comment by buske** [comment]
Thanks! Also, I kept testing and it looks like it's a bit more complex. On our server, the :9000 connections fail as stated. If I step off the server and request from my local machine, I can get through on http://...:9000. However, https://...:9000 fails with an SSL error:

```
*   Trying 198.202.94.165...
* Connected to mme.monarchinitiative.org (198.202.94.165) port 9000 (#0)
* Server aborted the SSL handshake
* Closing connection 0
curl: (35) Server aborted the SSL handshake
```

**Comment by jnguyenx** [comment]
Yes we don't have https support at the moment.

**Comment by buske** [comment]
Gotcha! Okay, thanks for all the help!
